version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_USER: shop
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: Shop
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    tty: true
    stdin_open: true
    networks:
      - lambda
networks:
  lambda:
    name: lambda
